version: '3.1'
services:
  middleware:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    environment: 
      - EPOCH_URL=https://sdk-mainnet.aepps.com
      - DATABASE_URL=postgres://middleware:middleware@db/middleware
    depends_on:
      - db

  db:
    image: postgres:10.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=middleware
      - POSTGRES_PASSWORD=middleware
      - POSTGRES_DB=middleware
    volumes: 
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mdw-postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
volumes:
    mdw-postgres-db-volume:
      external: false
