version: '3.1'
services:
  db:
    image: postgres:10.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: middleware
      POSTGRES_PASSWORD: middleware
      POSTGRES_DB: middleware
    volumes: 
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    expose: 
      - 5432
    ports:
      - "5432:5432"
  middleware:
    build:
      context: .
      dockerfile: ./middleware.Dockerfile
    ports:
      - "8000:8000"
      - "80:80"
    environment: 
      EPOCH_URL: https://sdk-testnet.aepps.com
      DATABASE_URL: postgres://middleware:middleware@db/middleware
    depends_on:
      - db